flags:
  llvm-general:
    shared-llvm: true
extra-package-dbs: []
extra-lib-dirs:
- /usr/local/lib
- /usr/local/opt/libffi/lib
packages:
- '.'
extra-deps:
- llvm-general-3.5.1.2
- llvm-general-pure-3.5.1.0
- text-1.2.2.1
- yaml-0.8.17.1
resolver: lts-5.13
